In [1]:
cd E:\karthi_m\wind

E:\karthi_m\wind


In [3]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [8]:
da=pd.read_csv('data1.csv')

In [9]:
da.head()

windspeed  airdensity  amb_temp  nac_direction blds_pitchangle  rtr_rpm  \
0        9.1    1.162127        27           61.8         (-2,-4)     14.1   
1        9.6    1.162127        27           61.8         (-2,-4)     14.4   
2        9.6    1.162127        27           61.8         (-2,-4)     14.4   
3       11.2    1.162127        27           65.2     (-0.1,-1.9)     14.5   
4       11.4    1.162127        27           66.6     (-0.1,-1.9)     14.5   

   gen_rpm wtg_state  
0   1305.0        ok  
1   1336.0        ok  
2   1330.0        ok  
3   1345.0        ok  
4   1344.0        ok

In [10]:
da.dtypes

windspeed          float64
airdensity         float64
amb_temp             int64
nac_direction      float64
blds_pitchangle     object
rtr_rpm            float64
gen_rpm            float64
wtg_state           object
dtype: object

In [11]:
da['blds_pitchangle'].value_counts()

(-2,-4)        36329
(0,30)         13945
(-0.1,-1.9)     8779
above 80.1      1531
(30.1,80)        205
Name: blds_pitchangle, dtype: int64

In [12]:
da['wtg_state'].value_counts()

ok                   44020
wind low              8658
curtailed             4186
Gen not conn          3896
high wind cut-out       29
Name: wtg_state, dtype: int64

In [13]:
da.isnull().sum() 

windspeed          0
airdensity         0
amb_temp           0
nac_direction      0
blds_pitchangle    0
rtr_rpm            0
gen_rpm            0
wtg_state          0
dtype: int64

In [14]:
y_ = da.apply(LabelEncoder().fit_transform)
y_.head()

windspeed  airdensity  amb_temp  nac_direction  blds_pitchangle  rtr_rpm  \
0         90           8         6            568                1      141   
1         95           8         6            568                1      144   
2         95           8         6            568                1      144   
3        111           8         6            602                0      145   
4        113           8         6            616                0      145   

   gen_rpm  wtg_state  
0     2805          3  
1     3036          3  
2     2982          3  
3     3124          3  
4     3114          3

In [15]:
x= da.drop(['wtg_state'],axis=1)
y= da['wtg_state']

In [16]:
x2=pd.get_dummies(x['blds_pitchangle'],drop_first=True)
x1=x.drop(['blds_pitchangle'],axis=1)
x= pd.concat([x1, x2], axis=1)

In [ ]:
#Naive bayes classifier 

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [18]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()

In [19]:
fit_=clf.fit(X_train,y_train)

In [20]:
y_pred=fit_.predict(X_test)

In [21]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[ 244,  106,    1,  313,  299],
       [   6,  716,    0,  310,    8],
       [   1,    0,    3,    2,    4],
       [1134, 2554,    2, 7280,   28],
       [ 432,   23,    0,   97, 1635]], dtype=int64)

In [22]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6499539413080668


In [ ]:
#Desicion tree classifier

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, stratify=y, random_state = 42)

In [29]:
# Fitting Classifier to the Training Set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',max_depth=3, random_state=42)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=42)

In [32]:
# Model performance on training set
y_pred=classifier.predict(X_test)

In [33]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8716936439005132


In [34]:
#Random forest 

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, stratify=y, random_state = 42)

In [37]:
# Feature Scaling
scaler = StandardScaler()
X_train_ = scaler.fit_transform(X_train)
X_test_ = scaler.transform(X_test)

In [38]:
#Creating the dependent variable class
factor = pd.factorize(da['wtg_state'])
da.wtg_state = factor[0]
definitions = factor[1]
print(da.wtg_state.head())
print(definitions)

0    0
1    0
2    0
3    0
4    0
Name: wtg_state, dtype: int64
Index(['ok', 'curtailed', 'Gen not conn', 'wind low', 'high wind cut-out'], dtype='object')


In [39]:
# Fitting Random Forest Classification to the Training set
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [40]:
y_pred=classifier.predict(X_test)

In [41]:
# Model performance on training set
y_pred =classifier.predict(X_test)

from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report

accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}".format(accuracy))
cm=confusion_matrix(y_test,y_pred)
print('Confusion Matrix: \n', cm)
print(classification_report(y_test, y_pred))

Accuracy: 0.93
Confusion Matrix: 
 [[  707    35     0   232     0]
 [   35   654     0   358     0]
 [    4     0     3     0     0]
 [   83   275     0 10647     0]
 [    0     0     0     0  2165]]
                   precision    recall  f1-score   support

     Gen not conn       0.85      0.73      0.78       974
        curtailed       0.68      0.62      0.65      1047
high wind cut-out       1.00      0.43      0.60         7
               ok       0.95      0.97      0.96     11005
         wind low       1.00      1.00      1.00      2165

         accuracy                           0.93     15198
        macro avg       0.90      0.75      0.80     15198
     weighted avg       0.93      0.93      0.93     15198

